//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLySoLenLop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GiangVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiangVien()
        {
            this.SoLenLops = new HashSet<SoLenLop>();
        }
    
        public string MaGVGD { get; set; }
        [Display(Name ="Họ tên giảng viên")]
        public string HoTenGVGD { get; set; }
        [Display(Name = "Password")]
        public string Matkhau { get; set; }
        [Display(Name = "Mã khoa")]
        public string MaKhoa { get; set; }
        [Display(Name = "Mã bộ môn")]
        public string MaBoMon { get; set; }

        public virtual BoMon BoMon { get; set; }
        public virtual Khoa Khoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoLenLop> SoLenLops { get; set; }
    }
}
