//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLySoLenLop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonHoc()
        {
            this.SoLenLops = new HashSet<SoLenLop>();
        }
        [Display(Name ="Mã môn học")]
        public string MaMH { get; set; }
        [Display(Name = "Tên môn học")]
        public string TenMH { get; set; }
        [Display(Name = "Số tiết lý thuyết")]
        public int SoTietLT { get; set; }
        [Display(Name = "Số tiết thực hành")]
        public int SoTietTH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoLenLop> SoLenLops { get; set; }
    }
}
