//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLySoLenLop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.CompilerServices;
    using System.Web.Mvc;

    public partial class SoLenLop
    {
        public int ID { get; set; }
        [Display(Name = "Học kỳ")]
        public int HocKy { get; set; }
        [Display(Name = "Năm học")]
        public string NamHoc { get; set; }
        [Display(Name = "Nhóm")]
        public int Nhom { get; set; }
        [Display(Name = "Ngày lên lớp")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime NgayLenLop { get; set; }
        [Display(Name = "Buổi")]
        public int Buoi { get; set; }
        [Display(Name = "Lý thuyết")]
        public int SoTietDayLT { get; set; }
        [Display(Name = "Thực hành")]
        public int SoTietDayTH { get; set; }
        [Display(Name = "Sinh viên vắng")]
        public string SinhVienVang { get; set; }
        [Display(Name = "Tóm tắt nội dung")]
        public string Tomtatnoidung { get; set; }
        [Display(Name = "Mã môn học")]
        public string MaMH { get; set; }
        [Display(Name = "Mã lớp")]
        public string MaLop { get; set; }
        [Display(Name = "Mã phòng")]
        public string MaPhong { get; set; }
        public string MaGVGD { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual Lop Lop { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
